# Navigation Bar Links
#   The weight parameter defines the order that the links will appear in.

[[main]]
    name = "Packages"
    url = "/packages/"
    weight = 1
[[main]]
    name = "Get Started"
    url = "/start/"
    weight = 2
[[main]]
    name = "Learn"
    url = "/learn/"
    weight = 3
[[main]]
    name = "Help"
    url = "/help/"
    weight = 4
[[main]]
    name = "Contribute"
    url = "/contribute/"
    weight = 5
[[main]]
    name = " "
    url = "/find/"
    pre = "<i class=\"fas fa-search fa-lg\"></i>"
    weight = 6
[[main]]
    pre = "<i class=\"fab fa-github fa-lg\"></i>"
    url = "https://github.com/tidymodels/"
    weight = 7

