# Navigation Bar Links
#   The weight parameter defines the order that the links will appear in.

[[main]]
    name = "Syllabus"
    url = "/syllabus/"
    weight = 1
[[main]]
    name = "Schedule"
    url = "/schedule/"
    weight = 2
[[main]]
    name = "Weekly Lessons"
    url = "/lessons/"
    weight = 3
[[main]]
    name = "Project"
    url = "/Project/"
    weight = 4
[[main]]
    name = "Help"
    url = "/help/"
    weight = 5
[[main]]
    name = "RStudio"
    url = "http://www.rstudio.com"
    pre = "<i class=\"fas fa-search fa-lg\"></i>"
    weight = 6
[[main]]
    name = "GitHub"
    pre = "<i class=\"fab fa-github fa-lg\"></i>"
    url = "https://github.com/tidymodels/"
    weight = 7

[[main]]
    name = "Sakai"
    pre = "<i class=\"fab fa-github fa-lg\"></i>"
    url = "https://github.com/tidymodels/"
    weight = 8


