---
title: "Formatting Guidelines & Tips"
author: ""
date: ""
output: 
  html_document:
    css: "sta210-project.css"
    toc: true
    toc_float: true
    toc_depth: 2
---

<style>
body, p, li{
  font-size: 18px; 
  font-weight: 400
}

h4 {
font-weight: bold; 
font-size: 22px;
color: #00897B;
}

</style>

## Suppress Code, Warnings, & Messages

- Include the following code in a code chunk at the top of your .Rmd file to suppress all code, warnings, and other messages. Use the code chunk header `{r set-up, include = FALSE}` to suppress this set up code. 

```{r include = FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE, 
                      message = FALSE)
```


## Resize figures

- Resize plots and figures, so you have more space for the narrative. 
    - **Resize individual figures**: Use the code chunk header `{r plot1, fig.height = 3, fig.width = 5}`, replacing `plot1` with a meaningful label and the height and width with values appropriate for your write up.
    - **Resize all figures**: Include the `fig_width` and `fig_height` options in your YAML header as shown below:

```
---
title: "Your Title"
author: "Team Name + Group Members"
output: 
  pdf_document:
    fig_width: 5
    fig_height: 3
---
```
 
Replace the height and width values with values appropriate for your write up.

## Arranging plots

Arrange plots in a grid, instead of one after the other. This is especially useful when displaying plots for exploratory data analysis and to check assumptions. 

- If you're using ggplot2 functions, the `patchwork` package makes it easy to arrange plots in a grid. See the documentation and examples [here](https://patchwork.data-imaginist.com/).

- If you're using base R function, i.e. when using the `binnedplot` function, put the code `par(mfrow = c(rows,columns))` before the code to make the plots. For example, `par(mfrow = c(2,3))` will arrange plots in a grid with 2 rows and 3 columns.

## Plot titles and axis labels

Be sure all plot titles and axis labels are visible and easy to read. 

- Use informative titles, <u>not</u> variable names, for titles and axis labels.
- Use `coord_flip()` to flip the *x* and *y* axes on the plot. This is useful if you a bar plot with an x-axis that is difficult to read due to overlapping text. See [Section 2.2.2](https://bookdown.org/skaltman/visualization-book/discrete-continuous.html). for an example.

## Formatting narrative

- Avoid using variable names in your narrative. Assume the reader only has access to your final write up and therefore won't be able to read your data dictionary. 
  - If you can't avoid using variable names in the write up, be sure the names are informative. For example, `cr_col` will be difficult for the reader to understand, use `carColor` instead.

- Use headers to clearly label each section. Make sure there is a space between the last `#` and the title, so the header renders correctly. For example, `###Section Title` will not render as header, but `### Section Title` will. 


## Model output

- Use the `kable` function to neatly output all tables and model output. This will also ensure all model coefficients are displayed. 
  - Use the `digits` option to display only 3 or 4 significant digits. 

- If you are running a multinomial logistic regression model, use the code chunk header `{r model, results = HIDE}` to suppress the iteration output.

## Resources 

- [R for Data Science](https://r4ds.had.co.nz/)
- [ggplot2 Reference](https://ggplot2.tidyverse.org/reference/index.html)
- [ggplot2: Elegant Graphics for Data Analysis](https://ggplot2-book.org/)
- [Data Visualization: A Practice Introduction](https://socviz.co/index.html)
- [Center for Data and Visualization Sciences consulting sessions on Zoom](https://library.duke.edu/data/about/schedule)
